name: Testing
on:
  push:
      branches: main
  workflow_dispatch:
jobs:
  Job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sample: [alter-state, array, callback, module, override, pass-variable, return-value, simple-call, stack-dump]
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: latest

      - name: Installing Dependencies
        run: sudo apt-get install libluajit-5.1-dev

      - name: Compiling 
        run: |
          haxelib install hxcpp --quiet
          haxelib dev hxluajit .
          cd examples/${{matrix.sample}}
          haxe build.hxml
